### ISSUE TITLE
Mobile Content Hub Category/Subcategory Page Issues

### ISSUE THREAD

**Issue by spaulenoff** [akcdotorg/akc.org#189]
New issue found on Mobile category/subcategory page: Possibly related to #170 
http://develop2.akc.org/content/dog-breeding/
http://develop2.akc.org/content/westminster-dog-show/live-coverage/
- Weird Code showing up in header **Resolved**
- Missing Mobile Navigation
- Not enough space between "featured articles" and Hero
- Tile Format is messed up, Swipeable dots are showing up within the tile itself instead of under the tile like it should be

![mobile category page](https://cloud.githubusercontent.com/assets/13648969/14530390/d6c37210-0226-11e6-8e63-9635ecd10859.png)

**Comment by kylejbertelsen** [comment]
The 'weird code' was indeed related to #170 -- that portion should be fixed now. Otherwise, unrelated to 170

**Comment by spaulenoff** [comment]
Confirming that I am seeing that first issue resolved

**Comment by kylejbertelsen** [comment]
Time spent:
2016-04-14: kjb: 2 hours - Repaired mobile navigation, restored styling on sliders

**Comment by spaulenoff** [comment]
Close but still seeing an issue where you are able to drag left and right on whole page. This does not occur on production.

Dev2:
![image](https://cloud.githubusercontent.com/assets/13648969/14539452/70a226de-024e-11e6-9e45-7642e8d0bfcb.png)

Prod:
![image](https://cloud.githubusercontent.com/assets/13648969/14539470/86e8b886-024e-11e6-8827-290cec55f61d.png)

**Comment by kylejbertelsen** [comment]
Moved menu + and - slightly left. Could not replicate draggability.

**Comment by spaulenoff** [comment]
I am still seeing dragging issue? have you checked browserstack or on your actual phone? If you have and still can't replicate, let me know and i will verify the changes are correct

**Comment by kylejbertelsen** [comment]
Found source of slight side-scroll: Our old friend minimee.

Stage is load-balanced, so minimee comes into play -- and when changing js/css on stage, we need to update the 'Cache-Busting' variable at Extensions > Minimee > Settings > Advanced. Doing so invalidates the server-cached css and js, allowing your changes to show.

This step will also be necessary in Production.

**Comment by spaulenoff** [comment]
Ok great! confirming it is no longer "bouncing" However can you move the +/- symbols back to their original placement as now they are slightly shifted over vs whats on prod

**Comment by spaulenoff** [comment]
@kylejbertelsen Please also add a comment with the issue and solution you found

**Comment by spaulenoff** [comment]
Verified on Prod
